### ISSUE TITLE
I‘m not Sybil Attacker Report

### ISSUE THREAD

**Issue by wsderf** [hop-protocol/hop-airdrop#432] opened 2022-05-19 03:31 UTC
These are the addresses I use often，Isn't it normal for a blockchain to have a dozen addresses? Do you have more than a dozen bank cards and credit cards. If one day Galaxy finds out about your dozen or so cards being put in jail for transferring money. do you feel innocent。
0x76967322893Cef3E8efa713dAf1Dc8347e081083
0xe636c37c8161d1097090534E294CABae78dcdcA3
0x45E81cF357f3F66A295e8A85e60832810801c660
0x858C5a5ddda4104d6efd731CfEf790EDcFf87841
0x74A4085839F18C19D6ce6af367b4Bc458aeC350C
0xFa18743f907ffe9BFF1a021b617e5134A4693390
0x4bBd5fCE20f25D6f185ff15AD037eB999feCBCB4
0x26C35CF6A0Ed1a821B25767548E16f324A3e2622
0x95F4b2aA12f3a85E2f3922352F0Cb8E7B4b96CbC
0x20B2e86D545768305D9629176fad5C0764fabB42
0xF7cE5f7A13DEE8BA402FA750088e478DB1f2b4F4
0xc647500D4778e9B41FA4423c4264b7185952E741
0x1815Eb802bC359e5a58cb9A1c19612F5620A2629
0x8b647F694db9C159C27a0C044550B81082F5df18
0xbD48B5051BB74030d23676058EF91e19B81E3F9F
0x2f7Dbf19C6901eCBF5b36f2c6667883fC533F8C6
0x3A91E8159FA5d0266475629A4704ee28E6396667

Why is this considered a witch attack by you? Whether your products are for users, how users use them, and how to cross-chain are still in accordance with your requirements. And those addresses, have you checked whether they are maliciously concatenated. Is it normal to transfer money between addresses? Can't you use a bank card to transfer money? I don't think there is strong evidence for this report.
I have used your project in the very early days. At that time, cross-chain was still very stuck. I will try to cross the chain one by one. Sometimes it is still waiting because there is no liquidity. Is this how you treat old users? I didn't even think about airdrops. Or only after someone told me. Who would have guessed that he was actually identified as a witch attack. I laughed

# Related Addresses

# Reasoning

# Methodology

# Rewards Address

**Comment by Bobb2906** [comment] 2022-05-19 04:00
Bro your english is tired🤣

**Comment by wsderf** [comment] 2022-05-19 04:04
I’m  chinese

**Comment by 1600770713** [comment] 2022-05-19 04:08
这是一个骗局

**Comment by wsderf** [comment] 2022-05-19 04:54
你们这群叼毛，随便按个图片就是女巫攻击了，攻击你麻痹

**Comment by hongchenjack** [comment] 2022-05-19 10:34
@wsderf  什么情况啊，已经给你取消hop币了？ 你干嘛了兄弟

**Comment by wsderf** [comment] 2022-05-19 10:52
> @wsderf 什么情况啊，已经给你取消了？

清0了，被人举报了。还是和别的地址加起来一起举报了。串联地址恶意举报

**Comment by shanefontaine** [comment] 2022-05-19 22:25
Because of this data provided, and more, your address won't be eligible for the airdrop, as it matches the expected behavior of a Sybil attacker.

I will now close this.

**Closed by shanefontaine** 2022-05-19 22:25 UTC

**Comment by wsderf** [comment] 2022-05-20 13:46
去你妈了隔壁
